CREATE TABLE MIASTA (
  ID_MIASTA INTEGER NOT NULL PRIMARY KEY,
  NAZWA VARCHAR2(20) NOT NULL,
  KOD_POCZTOWY VARCHAR2(6) NOT NULL UNIQUE
);

CREATE TABLE ADRESY (
  ID_ADRESU INTEGER NOT NULL PRIMARY KEY,
  ID_MIASTA INTEGER NOT NULL REFERENCES MIASTA(ID_MIASTA),
  ULICA VARCHAR2(30) NOT NULL,
  NR_BUDYNKU INTEGER NOT NULL,
  NR_LOKALU INTEGER NOT NULL
);

CREATE TABLE GRUPY (
    NR_GRUPY INTEGER NOT NULL PRIMARY KEY,
    NAZWA VARCHAR2(10) NOT NULL
);

CREATE TABLE OSOBY (
  ID_OSOBY INTEGER NOT NULL PRIMARY KEY,
  IMIE VARCHAR2(10) NOT NULL,
  NAZWISKO VARCHAR2(15) NOT NULL,
  NR_TEL INTEGER NOT NULL UNIQUE,
  ADRES_EMAIL VARCHAR2(20) NOT NULL,
  ID_ADRESU INTEGER NOT NULL REFERENCES ADRESY(ID_ADRESU)
);

CREATE TABLE STUDENCI (
    NR_ALBUMU INTEGER NOT NULL PRIMARY KEY,
    ID_OSOBY INTEGER NOT NULL REFERENCES OSOBY(ID_OSOBY),
    NR_GRUPY INTEGER NOT NULL REFERENCES GRUPY(NR_GRUPY)
);

CREATE TABLE WYKLADOWCY (
    ID_WYKLADOWCY INTEGER NOT NULL PRIMARY KEY,
    ID_OSOBY INTEGER NOT NULL REFERENCES OSOBY(ID_OSOBY),
    TYTUL VARCHAR2(20) NOT NULL
);

CREATE TABLE KONTO (
  ID_KONTA INTEGER NOT NULL PRIMARY KEY,
  ID_OSOBA INTEGER NOT NULL REFERENCES OSOBY(ID_OSOBY),
  TYP VARCHAR2(15) NOT NULL,
  LOGIN VARCHAR2(15) NOT NULL,
  PASSWORD VARCHAR2(15) NOT NULL,
  ZATWIERDZONE INTEGER NOT NULL
);

CREATE TABLE PRZEDMIOTY (
	ID_PRZEDMIOTU INTEGER NOT NULL PRIMARY KEY,
	NAZWA VARCHAR(20) NOT NULL
);

CREATE TABLE OCENY (
    ID_OCENY INTEGER NOT NULL PRIMARY KEY,
    OCENA NUMBER(1) NOT NULL,
    ID_PRZEDMIOTU INTEGER NOT NULL REFERENCES PRZEDMIOTY(ID_PRZEDMIOTU),
	NR_ALBUMU INTEGER NOT NULL REFERENCES STUDENCI(NR_ALBUMU)
);

CREATE TABLE GRUPA_ZAJECIOWA (
	NR_GRUPY INTEGER NOT NULL REFERENCES GRUPY(NR_GRUPY),
	ID_PRZEDMIOTU INTEGER NOT NULL REFERENCES PRZEDMIOTY(ID_PRZEDMIOTU),
	ID_WYKLADOWCY INTEGER NOT NULL REFERENCES WYKLADOWCY(ID_WYKLADOWCY)
);